name: Docs

on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using SPJFractals
            DocMeta.setdocmeta!(SPJFractals, :DocTestSetup, :(using SPJFractals); recursive=true)
            doctest(SPJFractals)'
      - run: julia --project=docs docs/make.jl
        env:
          JULIA_PKG_SERVER: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}